[setting]
mode = "number" # or "name" (need to specify name_list)

[data]
begin = 1
end = 50
name_list = [] # please get touch with developer if you want to use this feature

[style.font]
family = "Microsoft YaHei"
size = 40

[style.window]
opacity = 0.8