[setting]
mode = "number" # 或者 "name" 模式(需要配置name_list)

[data]
begin = 1
end = 50
name_list = [] # 使用此功能前需设置mode为"name"

[style.font]
family = "Microsoft YaHei"
size = 40

[style.window]
opacity = 0.8